### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by Helveg** [negrinho/writing_doctor#1]
Hi, I see that you are creating a linter for academic writing. I'm looking for collaborators that are interested in creating a python CLI tool for academic writing (including linting). Take a look at our plans in pwab/paperpy#1.

Is this a project you'd be interested in joining (we could develop this repository into a standalone linting package and use it as a dependency of the other project) and how far along towards a working linter are you?

**Comment by negrinho** [comment]
I've mainly developing this for personal use. I routinely use it on my writing and add new features as I find necessary, but I'm not planning on making more fully-featured in the near future. Happy to have anyone use the code if they find it useful. I have very limited time and attention to devote to it.
